version: '3.5'
services:
    app:
      container_name: sociozat-app
      build: 
        context: . # Use an image built from the specified dockerfile in the current directory.
        dockerfile: Dockerfile
      volumes:
        - ./:/go/src/sociozat
      ports:
        - "9000:9000"
      depends_on:
        - postgres-db
      #network_mode: "host"

    postgres-db:
      container_name: sociozat-postgres
      image: postgres:latest
      restart: always

      environment:
        POSTGRES_PASSWORD: "postgres"
        POSTGRES_DB: "postgres"
        POSTGRES_USER: "postgres"
        POSTGRES_HOST: "0.0.0.0"
        POSTGRES_PORT: 5432
        PGDATA: /var/lib/postgresql/data/pg_data
      ports:
        - "5432:5432"
      volumes:
        - ./.docker/database.sql:/docker-entrypoint-initdb.d/1-database.sql

    pgadmin:
      container_name: sociozat-pgadmin
      image: dpage/pgadmin4
      environment:
        PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
        PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      volumes:
        - pgadmin:/root/.pgadmin
      ports:
        - "${PGADMIN_PORT:-5050}:80"
      restart: unless-stopped
      logging:
        driver: none

volumes:
    app:
    postgres-db:
    pgadmin: